name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_PAC_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_PAC_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          # cache: yarn
          registry-url: "https://registry.npmjs.org"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        shell: bash
        run: yarn install --immutable
      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v5
